# HTTP Server
server:
  address: 0.0.0.0
  servlet:
    context-path: /gatewayservice
  port: 8765

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/discoveryservice/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
    #    ip-address: localhost
    homePageUrlPath: ${server.servlet.context-path}
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    leaseRenewalIntervalInSeconds: 10
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  security:
    enabled: false
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  #    web:
  #      base-path: /
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      routes:
        - id: infotypeservice
          uri: http://localhost:9000/infotypeservice/
          predicates:
            - Path=/infotypeservice/**
        - id: driverservice
          uri: http://localhost:2222/driverservice/
          predicates:
            - Path=/driverservice/**